name: drm
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  pointycastle: ^1.0.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
